version: "3"

services:
  app:
    container_name: app
    build:
      context: ./
    volumes:
      - ./:/usr/app
    environment:
      - APP_PORT=8080
      - DB_HOST=postgres
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    links:
      - postgres
  postgres:
    image: postgres:13.0-alpine
    volumes:
      - /home/data/vudo/postgres-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=vudo-dev
    container_name: postgres
