name: Deploy

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"
      - "**.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.8.9
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "vudo-backend"
          heroku_email: "dan.exxx1st@gmail.com"
